### Data Manipulation and Analysis with Pandas

Data manipulation and analysis  are key tasks in any data science or data analysis project. pandas provides a wide range of functions for data manipulation and analysis making it easier to clean, tranform and extract insights from data. in this lesson, we will cover various data manipulation and analysis techniques using pandas.

In [37]:
import pandas as pd

In [38]:
df=pd.read_csv('data1.csv')
## fetch the first 5 rows
df.head(5)

         date   category   value  product     sales   region
0  23-05-2024      Books  1161.0    Shirt  14978.77     West
1  20-01-2023  Groceries  3345.0    Shoes  16773.21     West
2  03-03-2023      Books  5666.0   Laptop  16987.12  Central
3  08-07-2024  Groceries  7576.0  Car Toy  12895.42     West
4  08-03-2024      Books  6794.0    Shirt  12184.28     East

In [39]:
df.tail(5)

           date   category   value product     sales   region
195  11-05-2023  Groceries  1969.0      TV   7184.54  Central
196  02-10-2023   Clothing  1121.0     NaN   9918.01    North
197  08-04-2023      Books  9097.0  Laptop  12735.29  Central
198  09-03-2023   Clothing  4945.0   Shoes   8625.64     East
199  23-04-2023  Groceries   328.0  Mobile  10464.84    South

In [40]:
df.describe()

             value         sales
count   199.000000    199.000000
mean   5145.105528  10452.920905
std    2811.145414   5675.999375
min     171.000000    504.350000
25%    2769.500000   5691.330000
50%    5278.000000   9918.010000
75%    7389.000000  15587.840000
max    9983.000000  19935.630000

In [41]:
df.dtypes

date         object
category     object
value       float64
product      object
sales       float64
region       object
dtype: object

In [42]:
## handling missing values
df.isnull()

      date  category  value  product  sales  region
0    False     False  False    False  False   False
1    False     False  False    False  False   False
2    False     False  False    False  False   False
3    False     False  False    False  False   False
4    False     False  False    False  False   False
..     ...       ...    ...      ...    ...     ...
195  False     False  False    False  False   False
196  False     False  False     True  False   False
197  False     False  False    False  False   False
198  False     False  False    False  False   False
199  False     False  False    False  False   False

[200 rows x 6 columns]

In [43]:
df.isnull().any()

date        False
category     True
value        True
product      True
sales        True
region       True
dtype: bool

In [44]:
# misssing values sum
df.isnull().sum()

date        0
category    1
value       1
product     2
sales       1
region      1
dtype: int64

In [45]:
df_filled=df.fillna(0)

In [46]:
## filling missing values with the mean of the column
df['Sales_fillNA']=df['sales'].fillna(df['sales'].mean())
df

           date   category   value  product     sales   region  Sales_fillNA
0    23-05-2024      Books  1161.0    Shirt  14978.77     West      14978.77
1    20-01-2023  Groceries  3345.0    Shoes  16773.21     West      16773.21
2    03-03-2023      Books  5666.0   Laptop  16987.12  Central      16987.12
3    08-07-2024  Groceries  7576.0  Car Toy  12895.42     West      12895.42
4    08-03-2024      Books  6794.0    Shirt  12184.28     East      12184.28
..          ...        ...     ...      ...       ...      ...           ...
195  11-05-2023  Groceries  1969.0       TV   7184.54  Central       7184.54
196  02-10-2023   Clothing  1121.0      NaN   9918.01    North       9918.01
197  08-04-2023      Books  9097.0   Laptop  12735.29  Central      12735.29
198  09-03-2023   Clothing  4945.0    Shoes   8625.64     East       8625.64
199  23-04-2023  Groceries   328.0   Mobile  10464.84    South      10464.84

[200 rows x 7 columns]

In [47]:
df.dtypes

date             object
category         object
value           float64
product          object
sales           float64
region           object
Sales_fillNA    float64
dtype: object

In [48]:
### renaming columns
df=df.rename(columns={'date':'Sales Date'})
df

     Sales Date   category   value  product     sales   region  Sales_fillNA
0    23-05-2024      Books  1161.0    Shirt  14978.77     West      14978.77
1    20-01-2023  Groceries  3345.0    Shoes  16773.21     West      16773.21
2    03-03-2023      Books  5666.0   Laptop  16987.12  Central      16987.12
3    08-07-2024  Groceries  7576.0  Car Toy  12895.42     West      12895.42
4    08-03-2024      Books  6794.0    Shirt  12184.28     East      12184.28
..          ...        ...     ...      ...       ...      ...           ...
195  11-05-2023  Groceries  1969.0       TV   7184.54  Central       7184.54
196  02-10-2023   Clothing  1121.0      NaN   9918.01    North       9918.01
197  08-04-2023      Books  9097.0   Laptop  12735.29  Central      12735.29
198  09-03-2023   Clothing  4945.0    Shoes   8625.64     East       8625.64
199  23-04-2023  Groceries   328.0   Mobile  10464.84    South      10464.84

[200 rows x 7 columns]

In [51]:
## change datatypes
df['Value_new']=df['value'].fillna(df['value'].mean()).astype(int)
df.head()

,Sales Date,category,value,product,sales,region,Sales_fillNA,Value_new
0,23-05-2024,Books,1161.0,Shirt,14978.77,West,14978.77,1161
1,20-01-2023,Groceries,3345.0,Shoes,16773.21,West,16773.21,3345
2,03-03-2023,Books,5666.0,Laptop,16987.12,Central,16987.12,5666
3,08-07-2024,Groceries,7576.0,Car Toy,12895.42,West,12895.42,7576
4,08-03-2024,Books,6794.0,Shirt,12184.28,East,12184.28,6794

In [52]:
df['New Value']=df['value'].apply(lambda x:x**2)
df.head()

,Sales Date,category,value,product,sales,region,Sales_fillNA,Value_new,New Value
0,23-05-2024,Books,1161.0,Shirt,14978.77,West,14978.77,1161,1347921.0
1,20-01-2023,Groceries,3345.0,Shoes,16773.21,West,16773.21,3345,11189025.0
2,03-03-2023,Books,5666.0,Laptop,16987.12,Central,16987.12,5666,32103556.0
3,08-07-2024,Groceries,7576.0,Car Toy,12895.42,West,12895.42,7576,57395776.0
4,08-03-2024,Books,6794.0,Shirt,12184.28,East,12184.28,6794,46158436.0

In [53]:
grouped_mean=df.groupby('product')['value'].mean()
print(grouped_mean)

product
Car Toy    5429.291667
Laptop     5295.354839
Mobile     5066.277778
Novel      4544.368421
Rice       5541.739130
Shirt      4826.363636
Shoes      5255.565217
TV         5423.807692
Name: value, dtype: float64

In [55]:
grouped_sum=df.groupby(['product','region'])['value'].sum()
print(grouped_sum)

product  region
Car Toy  Central    45853.0
         East       20174.0
         North      15206.0
         South      31943.0
         West       17127.0
Laptop   Central    36710.0
         East       23630.0
         North      17303.0
         South      45310.0
         West       41203.0
Mobile   Central    32166.0
         East       20143.0
         North      11774.0
         South       9405.0
         West       17705.0
Novel    Central     6191.0
         East       21152.0
         North      28452.0
         South      22558.0
         West        7990.0
Rice     Central    17898.0
         East       35249.0
         North      36825.0
         South      23210.0
         West       14278.0
Shirt    Central    44022.0
         East       47336.0
         North      20436.0
         South      18558.0
         West       28918.0
Shoes    Central    17366.0
         East       41285.0
         North       8250.0
         South      50632.0
         West        3345.0
TV       Central    21945.0
         East       36449.0
         North      20642.0
         South      35745.0
         West       25133.0
Name: value, dtype: float64

In [56]:
## aggregate multiple functions
grouped_agg=df.groupby('region')['value'].agg(['mean','sum','count'])
grouped_agg

                mean       sum  count
region
Central  4672.583333  224284.0     48
East     5707.395349  245418.0     43
North    4571.685714  160009.0     35
South    5651.452381  237361.0     42
West     5189.966667  155699.0     30

In [57]:
### merging and joining Dataframes
# Create sample Dataframe
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'],'Value1': [1,2,3,]})
df2 = pd.DataFrame({'Key': ['A','B','D'],'value2': [4,5,6]})

In [58]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [59]:
df2

  Key  value2
0   A       4
1   B       5
2   D       6

In [ ]:
# Merge Dataframe on the 'Key value'
pd.merge(df1,df2,on="Key",how="inner")  #inner means same parameter like A B are both in key df1 and df2

  Key  Value1  value2
0   A       1       4
1   B       2       5

In [61]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [62]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [63]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6