### Pandas-dataFrame And Series

Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. it provides two primary data structures: Series and dataFrame . A Series is a one-dimentional array-like object, while a DataFrame is a two-Dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [2]:
## Series
##A Pandas Series is a one-demensional array-like object that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("series \n",series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_data=pd.Series(data)
print(series_data)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [16]:
## dataframe
## create a Dataframe from a dictionary oof list

data={
      'Name':['Krish','John','Jack'],
      'Age':[25,30,45],
      'City':['Bangaloore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida
<class 'pandas.core.frame.DataFrame'>

In [6]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Bangaloore'],
       ['John', 30, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [10]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish' ,'Age':32,'City':'Bangalore'},
    {'Name':'John'  ,'Age':34,'City':'Bangalore'},
    {'Name':'vanie' ,'Age':38,'City':'Bangalore'},
    {'Name':'bappie','Age':31,'City':'Bangalore'}, 
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age       City
0   Krish   32  Bangalore
1    John   34  Bangalore
2   vanie   38  Bangalore
3  bappie   31  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [11]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [13]:
df=pd.read_csv('sales_data.csv')
df.tail(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [17]:
### Accessing data from Dataframe
df

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida

In [ ]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [22]:
df.loc[0]

Name         Krish
Age             25
City    Bangaloore
Name: 0, dtype: object

In [27]:
df.iloc[0][2]

C:\Users\Shantanu\AppData\Local\Temp\ipykernel_21400\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Bangaloore'

In [29]:
## Accessing a specified element
df

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida

In [31]:
df.at[2,'Age']

np.int64(45)

In [32]:
df.at[2,'Name']

'Jack'

In [35]:
## Acessing a specified element using iat
df.iat[2,2]

'Florida'

In [36]:
### data manipulation with DataFrame
df

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida

In [ ]:
## Adding a column
df['salary']=[50000,60000,70000]
df

    Name  Age        City  salary
0  Krish   25  Bangaloore   50000
1   John   30    New York   60000
2   Jack   45     Florida   70000

In [ ]:
## Remove a column # drop temporiry remove
df.drop('salary',axis=1)

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida

In [41]:
df

    Name  Age        City  salary
0  Krish   25  Bangaloore   50000
1   John   30    New York   60000
2   Jack   45     Florida   70000

In [42]:
df.drop('salary',axis=1,inplace=True)

In [43]:
df

    Name  Age        City
0  Krish   25  Bangaloore
1   John   30    New York
2   Jack   45     Florida

In [44]:
## add age to the column
df['Age']=df['Age']+1
df

    Name  Age        City
0  Krish   26  Bangaloore
1   John   31    New York
2   Jack   46     Florida

In [45]:
df.drop(0,inplace=True)

In [46]:
df

   Name  Age      City
1  John   31  New York
2  Jack   46   Florida